
# # Docker compose up ile çalışmaktadır.... (localde çalıştırılacaksa eğer)
version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: medical_rag_user
      POSTGRES_PASSWORD: medical_rag_password
      POSTGRES_DB: medical_rag_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    image: medical_rag_project
    depends_on:
      - db
    environment:
      POSTGRES_USER: medical_rag_user
      POSTGRES_PASSWORD: medical_rag_password
      POSTGRES_DB: medical_rag_db
      POSTGRES_HOST: db  # ÖNEMLİ! app/config.py'de host=db olmalı
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  init:
    build: .
    image: medical_rag_project
    depends_on:
      - db
    command: ["python", "init_db.py"]
    environment:
      POSTGRES_USER: medical_rag_user
      POSTGRES_PASSWORD: medical_rag_password
      POSTGRES_DB: medical_rag_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./app:/app
      
volumes:
  postgres_data:



