services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"  # host:container
    environment:
      POSTGRES_USER: medical_rag_user
      POSTGRES_PASSWORD: medical_rag_password
      POSTGRES_DB: medical_rag_db

volumes:
  postgres_data: